# Generated by Django 5.0 on 2023-12-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_darcek'),
    ]

    operations = [
        migrations.AddField(
            model_name='darcek',
            name='cena',
            field=models.FloatField(default=0.0),
        ),
    ]
