# Generated by Django 5.0 on 2023-12-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_darcek_cena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darcek',
            old_name='nametext',
            new_name='nazov',
        ),
        migrations.RenameField(
            model_name='darcek',
            old_name='presentfor',
            new_name='pre',
        ),
    ]
